public class AoC6B {
    //For both programs, the values must be pasted as a string in the getValues() method
    public static void main(String[] args){
        //Find how many questions were answered yes as a whole group
        String[] values = getValues();
        int total = 0;

        String character = "";
        String alphabet = "abcdefghijklmnopqrstuvwxyz";
        boolean inAll = true;

        for (int i = 0; i < values.length; i++){
            String[] persons = values[i].split("\n");
            for (int j = 0; j < alphabet.length(); j++){
                character = alphabet.substring(j,j+1);
                for (String k : persons){
                    if (inAll && k.indexOf(character) != -1){
                        inAll = true;
                    }
                    else { inAll = false; }
                }
                if (inAll) { total++; }
                inAll = true;
            }
        }

        System.out.println("Total number of questions agreed upon between groups: " + total);
    }

    public static String[] getValues(){
        String values = "gsvdkufnoawjmhp\n" +
                "wvhusojpnikgfadb\n" +
                "vshnpfedgwajkou\n" +
                "aujodhskfvnpgw\n" +
                "okpdnwhsfvjguqa\n" +
                "\n" +
                "juedvq\n" +
                "vqeduj\n" +
                "veqdju\n" +
                "eqduvj\n" +
                "\n" +
                "cdajbuernxm\n" +
                "mnucjearxbd\n" +
                "axrmdejuncb\n" +
                "jrebucmdxna\n" +
                "\n" +
                "kutplibdoqzfvhw\n" +
                "qcewmrkdvhl\n" +
                "qobdwvlkgxhpasyjn\n" +
                "\n" +
                "psbjhnatxe\n" +
                "pnaxesjhbt\n" +
                "tpxhbnseaj\n" +
                "\n" +
                "yskvjqacinfdrphwltxgzomueb\n" +
                "jwprnxzvkeofthuqbyimadgslc\n" +
                "\n" +
                "hzwepdg\n" +
                "lwf\n" +
                "wy\n" +
                "lw\n" +
                "rw\n" +
                "\n" +
                "sdgateubqmznhjk\n" +
                "xyphltd\n" +
                "\n" +
                "dbhl\n" +
                "hdlb\n" +
                "dbhl\n" +
                "hbld\n" +
                "\n" +
                "inkxywsbgjuvpztrecadqmhf\n" +
                "qkaxszcujwvmbhdietpgr\n" +
                "krupsdgibzecxwvhqatmj\n" +
                "qtpxerobhisgcumkwjvdaz\n" +
                "\n" +
                "bgakcmh\n" +
                "gxasvzu\n" +
                "\n" +
                "cjtrvhinaqsbpk\n" +
                "jvxtspaqbhkfnrc\n" +
                "\n" +
                "nab\n" +
                "bex\n" +
                "qmkudf\n" +
                "\n" +
                "uot\n" +
                "out\n" +
                "tuo\n" +
                "uto\n" +
                "out\n" +
                "\n" +
                "sbtkzf\n" +
                "hbkfzs\n" +
                "szbkf\n" +
                "fuzksbx\n" +
                "jskrzbf\n" +
                "\n" +
                "dkphfoybsagcrnq\n" +
                "oybunchapqrdks\n" +
                "bokpysdhqnarc\n" +
                "\n" +
                "bchumknwairvlf\n" +
                "cvbuhwzirkalfy\n" +
                "\n" +
                "bwnseiaoqyjf\n" +
                "josqanfbew\n" +
                "nealmqbfwojs\n" +
                "jqnbfaoesw\n" +
                "\n" +
                "sowzuji\n" +
                "wojizu\n" +
                "wzojiu\n" +
                "jwozui\n" +
                "ujiwoz\n" +
                "\n" +
                "kcopqbt\n" +
                "tpkudorbc\n" +
                "pmtwogjb\n" +
                "\n" +
                "uxkfthszqdbelomwri\n" +
                "tlusezbomwfqrdxhki\n" +
                "rsdfkbteoqilzmxhuw\n" +
                "bwkqmdsxhrfulietoz\n" +
                "izkwomsdlbfxetqhru\n" +
                "\n" +
                "kzhwyodlvpt\n" +
                "kvfhldwpo\n" +
                "lvhypokdw\n" +
                "opwjhvdkcl\n" +
                "kpahtdolvw\n" +
                "\n" +
                "cldyjpuitah\n" +
                "upcthlijyda\n" +
                "icdauhpytj\n" +
                "haypidtucj\n" +
                "jidaptcyhuo\n" +
                "\n" +
                "mi\n" +
                "ti\n" +
                "qjwiz\n" +
                "oudehsxyiv\n" +
                "bpirjl\n" +
                "\n" +
                "stlyornuk\n" +
                "cxapqwie\n" +
                "\n" +
                "kharunjiebzvoy\n" +
                "gvaihtklnqmcebf\n" +
                "\n" +
                "t\n" +
                "lt\n" +
                "t\n" +
                "\n" +
                "ohca\n" +
                "lznkumqfgyjsbeot\n" +
                "owxdivpr\n" +
                "\n" +
                "dy\n" +
                "yo\n" +
                "xsy\n" +
                "yo\n" +
                "pyrvh\n" +
                "\n" +
                "iaxp\n" +
                "afpikux\n" +
                "\n" +
                "hpsfqrnevzxl\n" +
                "fnrsvexzhqup\n" +
                "\n" +
                "cp\n" +
                "fpc\n" +
                "cp\n" +
                "\n" +
                "nbuojxgqckrwzspehf\n" +
                "mhguoxsfkejwcq\n" +
                "kedqujsomfxhwcvg\n" +
                "ouqefsxchgjkw\n" +
                "qcjohwxfseugk\n" +
                "\n" +
                "rybnlomq\n" +
                "fmxsngauo\n" +
                "embkon\n" +
                "nlmvob\n" +
                "bomhnv\n" +
                "\n" +
                "gptixlduzjeqkorsamwnh\n" +
                "pgzwohfjkuvbtylmc\n" +
                "\n" +
                "thcgo\n" +
                "vhrlxmo\n" +
                "\n" +
                "kbfgmhpzoqysac\n" +
                "ockazbsmhpgqfy\n" +
                "kmcqfyzhapgsxb\n" +
                "qcfdlwyarzuskhmbg\n" +
                "\n" +
                "surovlcihp\n" +
                "irvlpuhosc\n" +
                "\n" +
                "rd\n" +
                "d\n" +
                "td\n" +
                "d\n" +
                "\n" +
                "koasgulh\n" +
                "kroumtzl\n" +
                "yubkwolnpj\n" +
                "\n" +
                "dqykvasneb\n" +
                "easknpbovyjd\n" +
                "\n" +
                "wqvop\n" +
                "nwqvpo\n" +
                "wovfrqizh\n" +
                "onqpwv\n" +
                "\n" +
                "uskotfndjeplixhycbqrmw\n" +
                "mbxoewypcfdhistn\n" +
                "ydtvpbfemcnsihoxw\n" +
                "ynwbtosmcipxhfde\n" +
                "\n" +
                "urgvbqechawznsjltixody\n" +
                "swdbnevcatrflguhziyoqxj\n" +
                "sgiwelhanovrbjuzyqtdcx\n" +
                "vyenojuhxwzbtigsdqarkcl\n" +
                "\n" +
                "jxcwblszo\n" +
                "khrwvnbdolgjufyz\n" +
                "\n" +
                "n\n" +
                "r\n" +
                "d\n" +
                "r\n" +
                "bd\n" +
                "\n" +
                "tolrypvdwmb\n" +
                "lwrmopdvybt\n" +
                "rdybwmvplto\n" +
                "vlwpyrbmotd\n" +
                "ybolwtvprmd\n" +
                "\n" +
                "radvoplnq\n" +
                "lrqpondva\n" +
                "lpanovqrd\n" +
                "lpanvoqdr\n" +
                "dqorvalpn\n" +
                "\n" +
                "fvxca\n" +
                "vacfx\n" +
                "fvcxa\n" +
                "\n" +
                "jbeixdakgolpfhqyntw\n" +
                "purbsxvjfwhetlmcnz\n" +
                "\n" +
                "jztfgbmnkadiehv\n" +
                "djhpntcizmkgvbfe\n" +
                "btegdfknizvmhjl\n" +
                "igbdeztjfkhmnv\n" +
                "iqvtgejanzfdbhmk\n" +
                "\n" +
                "jpi\n" +
                "ijp\n" +
                "ijp\n" +
                "\n" +
                "kydp\n" +
                "viykd\n" +
                "dgyqmftwx\n" +
                "vdye\n" +
                "\n" +
                "sewpkrvh\n" +
                "ekorswnp\n" +
                "\n" +
                "bplerysifmzvwoncjxqk\n" +
                "nsbeqowitcpjymxvl\n" +
                "\n" +
                "nexbskamprd\n" +
                "xsmdbkaupner\n" +
                "dsbnekarctvmpx\n" +
                "nkapxcbsmrlde\n" +
                "ezfdhnakwrsmyxpb\n" +
                "\n" +
                "olnuzvxcgpdtfb\n" +
                "tgzcfdbnxp\n" +
                "\n" +
                "vjliksorxpmwecaznu\n" +
                "giuoxsvnzewljpmc\n" +
                "\n" +
                "fuljpkt\n" +
                "cplftukj\n" +
                "lfptjku\n" +
                "futpjlk\n" +
                "\n" +
                "tqcgihveyswu\n" +
                "ywvqecthgs\n" +
                "cqhwetvsyg\n" +
                "qvshwcegty\n" +
                "gyctwqsfvhe\n" +
                "\n" +
                "uhezlyxwvpcidr\n" +
                "hvucplszbxywer\n" +
                "\n" +
                "jchyntk\n" +
                "revwzsm\n" +
                "kdn\n" +
                "\n" +
                "cotikdlpxauzb\n" +
                "uxzptoksqbdiw\n" +
                "\n" +
                "nqvruwhtombs\n" +
                "tebfnykzmlgcj\n" +
                "\n" +
                "ciwkhzbmgfqo\n" +
                "uwmzgbcoihqkfs\n" +
                "fkwmziohcgbq\n" +
                "\n" +
                "shezgrvq\n" +
                "gprveokq\n" +
                "\n" +
                "jvqcdiuyrnpgh\n" +
                "dyjqvhrpic\n" +
                "xjiklpfzmthrwdsyqv\n" +
                "pdyvochrunaqjgi\n" +
                "\n" +
                "denpjgywacrk\n" +
                "jbypwarecukdgn\n" +
                "zacqyxdgejrmpwkfnh\n" +
                "uwldpkrgaenjcy\n" +
                "\n" +
                "q\n" +
                "mq\n" +
                "q\n" +
                "\n" +
                "d\n" +
                "c\n" +
                "d\n" +
                "d\n" +
                "\n" +
                "cdazeitlrpxnfqs\n" +
                "nrqxelfocsihpz\n" +
                "cnkveyiujlbzfgrpxq\n" +
                "cqznxrfliedp\n" +
                "\n" +
                "qicgkpjzlxonv\n" +
                "cijozlhkqxnp\n" +
                "pgkcnloyxzj\n" +
                "japmxlknszotc\n" +
                "\n" +
                "bytg\n" +
                "mwetjayhgiup\n" +
                "gyt\n" +
                "ygt\n" +
                "tyg\n" +
                "\n" +
                "zx\n" +
                "elxz\n" +
                "z\n" +
                "vncto\n" +
                "\n" +
                "nryw\n" +
                "rywn\n" +
                "\n" +
                "takqgijzforxpshm\n" +
                "ztmrxfqgsiphjaok\n" +
                "\n" +
                "fsaoqe\n" +
                "wcavsldeytn\n" +
                "auoekhzsi\n" +
                "hgseja\n" +
                "\n" +
                "whqyvldpintefaxgurjc\n" +
                "xluqrgsvnacykptefbdhmj\n" +
                "\n" +
                "oylknhsgmpawziqte\n" +
                "znhmatkpolsw\n" +
                "pkvmtznhlwsoa\n" +
                "onzamhltkpsw\n" +
                "\n" +
                "zs\n" +
                "zs\n" +
                "zs\n" +
                "sz\n" +
                "\n" +
                "e\n" +
                "a\n" +
                "\n" +
                "xmi\n" +
                "gahfrd\n" +
                "yt\n" +
                "jmy\n" +
                "nqy\n" +
                "\n" +
                "zkbtfdjom\n" +
                "ot\n" +
                "uoqtr\n" +
                "eot\n" +
                "\n" +
                "g\n" +
                "er\n" +
                "g\n" +
                "g\n" +
                "\n" +
                "ncvwupezd\n" +
                "cnvdwzpeu\n" +
                "cuwnzvedp\n" +
                "cdnzevwpu\n" +
                "\n" +
                "bkuwcsv\n" +
                "bqcsgwve\n" +
                "mbhcovjsw\n" +
                "qwrnbeycsv\n" +
                "lisvbwc\n" +
                "\n" +
                "vlys\n" +
                "omvzl\n" +
                "ptlejv\n" +
                "xylv\n" +
                "vxol\n" +
                "\n" +
                "mqgohwtz\n" +
                "rqomlcw\n" +
                "\n" +
                "rgopxhkslqcjmzbatnd\n" +
                "phgzmojlstadqrxkbn\n" +
                "\n" +
                "pcbziv\n" +
                "pivzbc\n" +
                "jilczbpv\n" +
                "\n" +
                "gmrecszl\n" +
                "zgrecslm\n" +
                "melzcrgs\n" +
                "gezcrlsm\n" +
                "mcsezrlg\n" +
                "\n" +
                "ceotvxaydplfiu\n" +
                "vbzcaxuokwd\n" +
                "\n" +
                "gy\n" +
                "g\n" +
                "\n" +
                "lj\n" +
                "neocbiqjt\n" +
                "\n" +
                "foyawivmhs\n" +
                "fayowsmzrv\n" +
                "mksfowvzayg\n" +
                "\n" +
                "sivthk\n" +
                "yh\n" +
                "lh\n" +
                "ybhq\n" +
                "hy\n" +
                "\n" +
                "fk\n" +
                "ka\n" +
                "vka\n" +
                "qhjxrzmckpb\n" +
                "kf\n" +
                "\n" +
                "s\n" +
                "s\n" +
                "s\n" +
                "\n" +
                "iyth\n" +
                "tyhri\n" +
                "yrtaih\n" +
                "htyi\n" +
                "utifydhq\n" +
                "\n" +
                "hwxd\n" +
                "xhwd\n" +
                "hxwdb\n" +
                "\n" +
                "kfhsvbjdwxcnt\n" +
                "dbfjhsctkvw\n" +
                "sogzdhjqiwmlyuvf\n" +
                "\n" +
                "v\n" +
                "nyx\n" +
                "v\n" +
                "i\n" +
                "\n" +
                "ncimwelvbudtp\n" +
                "piwvudaer\n" +
                "\n" +
                "aktpdrhm\n" +
                "dtapkhr\n" +
                "dhapktri\n" +
                "taprnhdko\n" +
                "krpdhta\n" +
                "\n" +
                "fvpaxk\n" +
                "zgmrwja\n" +
                "ar\n" +
                "\n" +
                "vxoisla\n" +
                "olisvxa\n" +
                "kioqvrlxjhsya\n" +
                "oixgalsv\n" +
                "savloix\n" +
                "\n" +
                "ac\n" +
                "gr\n" +
                "c\n" +
                "tl\n" +
                "c\n" +
                "\n" +
                "fndwqsruzagei\n" +
                "dwunqfaesgzri\n" +
                "bzarmfnqwuisgde\n" +
                "\n" +
                "jr\n" +
                "rj\n" +
                "jr\n" +
                "jr\n" +
                "\n" +
                "zrevhj\n" +
                "xigdmqatk\n" +
                "wjlpzvsy\n" +
                "\n" +
                "qijznvobp\n" +
                "nzbojivdpc\n" +
                "vzipojnb\n" +
                "\n" +
                "srbtecvpixam\n" +
                "hdvctplmfxuow\n" +
                "\n" +
                "bf\n" +
                "bf\n" +
                "bf\n" +
                "bfex\n" +
                "\n" +
                "g\n" +
                "g\n" +
                "g\n" +
                "g\n" +
                "mag\n" +
                "\n" +
                "b\n" +
                "y\n" +
                "b\n" +
                "\n" +
                "vmbwhdfiqteglnpkxucjoa\n" +
                "wmqdconxbuaetjlgphivkf\n" +
                "upadfnhkwtjioqcbvxelmg\n" +
                "gofjubptnmkelihwxacqvd\n" +
                "\n" +
                "alev\n" +
                "evla\n" +
                "alve\n" +
                "avel\n" +
                "aelv\n" +
                "\n" +
                "uceyogrhl\n" +
                "oqcafluvhewgr\n" +
                "ugcxlhorpez\n" +
                "nduzshrceglox\n" +
                "odmgbeucrplh\n" +
                "\n" +
                "ugesfliovyzja\n" +
                "nlizsujfadgo\n" +
                "lfguaszotij\n" +
                "osznifulgadkj\n" +
                "xadguljioszf\n" +
                "\n" +
                "kpgve\n" +
                "vqsfezungalxidb\n" +
                "gwteov\n" +
                "gpvcyjrmeh\n" +
                "\n" +
                "apuonkxtc\n" +
                "xithys\n" +
                "hfvtsx\n" +
                "\n" +
                "pgtzamyqeu\n" +
                "gtiuwpcqzvya\n" +
                "tpqauezyg\n" +
                "\n" +
                "souvmglcqbekzi\n" +
                "miuzvksocgqbel\n" +
                "gzqkmsubevolci\n" +
                "\n" +
                "ndvahciz\n" +
                "jaoyhepsbirw\n" +
                "\n" +
                "bghijfkotcxwu\n" +
                "uaokxsfbleyhgqr\n" +
                "hucfokpwbxg\n" +
                "nbfuztgovhxk\n" +
                "\n" +
                "zghianxtlq\n" +
                "qthdvingxalkz\n" +
                "wfqnixgteza\n" +
                "\n" +
                "lhzcrodupwqsv\n" +
                "phsvrzcldoqwu\n" +
                "hogspqwcvukdz\n" +
                "hwzpucdsqvrol\n" +
                "\n" +
                "txkqmsfbglhnoypaduiv\n" +
                "navlozmpthwsbkiqxdfu\n" +
                "\n" +
                "gidnojlbtfpskuwavyxczr\n" +
                "irvsyznbtedxougfwc\n" +
                "sovxhcqdbwytzmugrinf\n" +
                "\n" +
                "mcjnraketsgvqyxpbuwlhzdof\n" +
                "kqudanprgiejcftzlywhsoxmb\n" +
                "rcxmkdqfohjzgtsalbpunywe\n" +
                "\n" +
                "o\n" +
                "cm\n" +
                "rc\n" +
                "m\n" +
                "\n" +
                "tmkbedxgzsw\n" +
                "tdgmsxbzkernw\n" +
                "ktdbxzsemgw\n" +
                "gwkmestbdxz\n" +
                "xzdewgtmskb\n" +
                "\n" +
                "evpdgzcu\n" +
                "gepcvzu\n" +
                "vegzpuc\n" +
                "vpuzgec\n" +
                "cvpgeuz\n" +
                "\n" +
                "wfsadgtuizejmylxq\n" +
                "aspmuqigbxeljdtwfy\n" +
                "\n" +
                "ygbtdp\n" +
                "tye\n" +
                "fryaitjcukhl\n" +
                "ytdm\n" +
                "\n" +
                "jfm\n" +
                "m\n" +
                "m\n" +
                "\n" +
                "cl\n" +
                "cl\n" +
                "lc\n" +
                "\n" +
                "qbodnftrsygi\n" +
                "iztorbfskqdvng\n" +
                "onpsgqrdtif\n" +
                "mnrofcuqwdtils\n" +
                "\n" +
                "mhavcgzlrtbo\n" +
                "jrldgavzqbcxoh\n" +
                "\n" +
                "pshtdbifrvzqmklyae\n" +
                "tfajgrpkidzyhslebmvq\n" +
                "\n" +
                "cuzbjepnvis\n" +
                "isjbenvyzlcup\n" +
                "nagieshzcpqmfuvbj\n" +
                "ezvpsjrnciub\n" +
                "\n" +
                "ywgdsafzuxbrmhvqkljnoipc\n" +
                "hjcntvrzwdfbxksyiqolpumag\n" +
                "kwvpybmjeoualxcsqgidhfnrz\n" +
                "\n" +
                "zubvkn\n" +
                "cuwfsnv\n" +
                "\n" +
                "isknfdalujeg\n" +
                "hikagvpzx\n" +
                "\n" +
                "szgfhjtxid\n" +
                "stdgjzxfih\n" +
                "xghsjfdzit\n" +
                "gfjixszhtd\n" +
                "fzjshdtixg\n" +
                "\n" +
                "uibgxka\n" +
                "abigukx\n" +
                "xubakgi\n" +
                "gxabiuky\n" +
                "bkaxgui\n" +
                "\n" +
                "tjzor\n" +
                "slaore\n" +
                "gxwnoifudmcqvpk\n" +
                "obhr\n" +
                "tyo\n" +
                "\n" +
                "q\n" +
                "y\n" +
                "e\n" +
                "r\n" +
                "ifdcxzm\n" +
                "\n" +
                "fvtqrjsblkhuoiey\n" +
                "gyfnizlqupvscobt\n" +
                "bouiftlcvqsy\n" +
                "qdvlyfiusgotb\n" +
                "qvbycwsifluto\n" +
                "\n" +
                "ifmnxbcvpkylruh\n" +
                "nckrmfphluixvby\n" +
                "vbcmxyhurnpilfk\n" +
                "suiqbvyrxcphmfnlk\n" +
                "ynuxkrfvibclpmh\n" +
                "\n" +
                "pmvdyexsoilatqfgk\n" +
                "lpidgatmqevkxyso\n" +
                "gkpsaoleymqxvtdi\n" +
                "gmvxeyplqdoasitk\n" +
                "vkpdylstquegaiomx\n" +
                "\n" +
                "ymogxuswkce\n" +
                "vbxznpscg\n" +
                "xlcgs\n" +
                "xclbdsng\n" +
                "\n" +
                "zovwtiy\n" +
                "zrjlciov\n" +
                "ksxefuvqdam\n" +
                "\n" +
                "cwvsx\n" +
                "xeuwyhsfb\n" +
                "\n" +
                "hxwgolksbrdmpifye\n" +
                "lwpyefxmiohdnbksgr\n" +
                "gzoehypbldxikmwtrfs\n" +
                "sdlwpeymxifrbghok\n" +
                "glmbhykiofdxpwervs\n" +
                "\n" +
                "ndcphgqfuvsekaxozri\n" +
                "xofkqnbschdaveruizgp\n" +
                "\n" +
                "ptkvdhjaw\n" +
                "skhtapidwjn\n" +
                "thunakpjwd\n" +
                "eaglphkdtjcfw\n" +
                "\n" +
                "pnezvfgiouahmslkdxcrqb\n" +
                "fpiqsecxaukbvzgnorjhwdm\n" +
                "\n" +
                "emcwblgxuvnkzrdsoyjf\n" +
                "rvsxeugkmwzfncojlb\n" +
                "nhbiclvskjrupgxzfeomw\n" +
                "gcxlbjozeiufwnskvrm\n" +
                "eonjkwbzfxgpruvcmsl\n" +
                "\n" +
                "ntgia\n" +
                "ia\n" +
                "ai\n" +
                "\n" +
                "scoernukhwtigpd\n" +
                "bogiserhpucnkt\n" +
                "\n" +
                "eaipzg\n" +
                "gne\n" +
                "lughe\n" +
                "\n" +
                "tbipylmnrague\n" +
                "tbargijepmhuynl\n" +
                "triyzgupnbmale\n" +
                "prtnumgaibley\n" +
                "peblaytmgnrui\n" +
                "\n" +
                "rqlsepfhiv\n" +
                "fvelqphsri\n" +
                "ilfhvqerps\n" +
                "fheqplsvir\n" +
                "sfpvehirlq\n" +
                "\n" +
                "jciwxfbhqkadgzloprnuvsty\n" +
                "qwouetsmhykavxfbjzrglc\n" +
                "\n" +
                "fjmz\n" +
                "mjczf\n" +
                "unkzjm\n" +
                "\n" +
                "gebyncxsphfokwm\n" +
                "gmchsnbwkpfyxeo\n" +
                "fybkhcesogxpwmn\n" +
                "\n" +
                "ud\n" +
                "whjn\n" +
                "\n" +
                "ihm\n" +
                "hmi\n" +
                "\n" +
                "p\n" +
                "p\n" +
                "yp\n" +
                "sp\n" +
                "\n" +
                "ytrwx\n" +
                "yrtxw\n" +
                "\n" +
                "p\n" +
                "d\n" +
                "\n" +
                "ieltygdukac\n" +
                "yiudeakg\n" +
                "kpegdaiyu\n" +
                "audykegi\n" +
                "aeqydwiguk\n" +
                "\n" +
                "lb\n" +
                "ei\n" +
                "\n" +
                "zjvctfndgiqbeu\n" +
                "abfwndutvecqigz\n" +
                "fznbdutevigcq\n" +
                "qtvzfnueibdcg\n" +
                "\n" +
                "g\n" +
                "i\n" +
                "x\n" +
                "g\n" +
                "g\n" +
                "\n" +
                "qhm\n" +
                "lq\n" +
                "nq\n" +
                "pqsb\n" +
                "lvq\n" +
                "\n" +
                "qnxpslvajf\n" +
                "xuavcnst\n" +
                "nsyabxv\n" +
                "\n" +
                "ocu\n" +
                "uco\n" +
                "acoux\n" +
                "cluo\n" +
                "coun\n" +
                "\n" +
                "jtgzodebq\n" +
                "ojztqdgbe\n" +
                "oejrqzgtbda\n" +
                "tjzbqedgo\n" +
                "gzqtejobd\n" +
                "\n" +
                "ubglorcsyvmxd\n" +
                "oentwfgulpqikdcbzhj\n" +
                "\n" +
                "jwkmxdnyvbiz\n" +
                "qebnoyfz\n" +
                "\n" +
                "bepdfi\n" +
                "ikepbof\n" +
                "\n" +
                "cofgekndbatpruhqmwvsiy\n" +
                "bsqtrakeudopghvyfmcnw\n" +
                "qgusdwvabytmfkcnehorp\n" +
                "qfhruygwkvmbpaoestcdn\n" +
                "prmkbuvynseatdoqwfhcg\n" +
                "\n" +
                "enczdvbkiyjgruqp\n" +
                "bdiqvwjurpycngzk\n" +
                "bnrcejupvqiwgzkyd\n" +
                "pqgybrcjzkudonvi\n" +
                "\n" +
                "fygasxjwrb\n" +
                "ijsgafwyrbx\n" +
                "syjawbxgfr\n" +
                "wfbrgvsjyax\n" +
                "\n" +
                "xtp\n" +
                "bfnzuadh\n" +
                "xlce\n" +
                "\n" +
                "rxmeqcbv\n" +
                "\n" +
                "fjtdihkrbyn\n" +
                "htfjyinkgdrb\n" +
                "fibgtkdryhnj\n" +
                "hkbnjrftidy\n" +
                "intbxjrkfdyh\n" +
                "\n" +
                "nhkiqjocfgxmrvwetd\n" +
                "ghnfdjvqtxwermokci\n" +
                "xnrtfkhdwcmjvoeigq\n" +
                "mcvfjhwiqtnrekogdx\n" +
                "imhxgjwrodtcknqvef\n" +
                "\n" +
                "sabwqu\n" +
                "yqamws\n" +
                "\n" +
                "usei\n" +
                "xkvnyfi\n" +
                "\n" +
                "rcewysztbiamhpgldj\n" +
                "kibrfndmgeazcsh\n" +
                "adrzgchmwjsbie\n" +
                "\n" +
                "pnrwvx\n" +
                "lwjxnu\n" +
                "vwxinb\n" +
                "pfxybwng\n" +
                "\n" +
                "wnvxgfdkubzrmip\n" +
                "kmjhoigltwbz\n" +
                "\n" +
                "znlgbx\n" +
                "fla\n" +
                "dl\n" +
                "l\n" +
                "l\n" +
                "\n" +
                "jgeqcikplduzxrwby\n" +
                "kwplxgcbndjqyizuer\n" +
                "ewrqujilgyxpdzcbk\n" +
                "\n" +
                "guteykxsqrfwhz\n" +
                "mhiurkswtqbxz\n" +
                "sdlqxvowujrhkz\n" +
                "\n" +
                "zrejn\n" +
                "nzrje\n" +
                "jnerz\n" +
                "rzjen\n" +
                "\n" +
                "fvkouigderaqbjth\n" +
                "eqrvwjinfltzpcuag\n" +
                "\n" +
                "stqcrpy\n" +
                "ctsqpyr\n" +
                "ptyqrsc\n" +
                "ymsqrcaptb\n" +
                "\n" +
                "egftpqosiv\n" +
                "ecjdqlnmwouf\n" +
                "spxaqofre\n" +
                "epogyfqi\n" +
                "\n" +
                "oxwgtshjqef\n" +
                "pbtgjfeqhnoxw\n" +
                "jfhewygoxtq\n" +
                "\n" +
                "jwavgo\n" +
                "ogevbwdjai\n" +
                "ogvahjw\n" +
                "wrajvog\n" +
                "ogsjwarv\n" +
                "\n" +
                "rpucvg\n" +
                "cgpr\n" +
                "htfelpc\n" +
                "\n" +
                "hqrwapscubelovxntd\n" +
                "jisztpnbcahlfdoqmvexgk\n" +
                "\n" +
                "pmadwutiejznofcgvsbqyxh\n" +
                "qvmzbaisgfcunwjexhpdktyo\n" +
                "xtvsdnqaucyehgzbjiopwmf\n" +
                "\n" +
                "vjqih\n" +
                "himjwdv\n" +
                "hsojivb\n" +
                "jtrklivehyg\n" +
                "mvnaizoqpfxhj\n" +
                "\n" +
                "j\n" +
                "j\n" +
                "j\n" +
                "j\n" +
                "j\n" +
                "\n" +
                "dpnwmtvklc\n" +
                "ndjpkm\n" +
                "ndmpk\n" +
                "ndmpk\n" +
                "ndmpk\n" +
                "\n" +
                "ucojsptiqymhewbxvrfdkngl\n" +
                "ebpjwuxrdqkmsochvfgliznt\n" +
                "\n" +
                "esroiaqdbxnjhut\n" +
                "xibuqhmensdajo\n" +
                "feukjbahdxwqnsiocv\n" +
                "\n" +
                "vkxzclpmtujngerawod\n" +
                "azdrgcenvjxptkuolmw\n" +
                "onrluajvcgewpdzkmtx\n" +
                "xamlobkrvzwpjgnucdte\n" +
                "tvenjdmlzpwugkoracx\n" +
                "\n" +
                "ywpfhztklgjmoien\n" +
                "nyelduixgvwmojpzhtk\n" +
                "lehpigtmoknjyzw\n" +
                "gmhwzokylpnteji\n" +
                "tmypejhwgzlniko\n" +
                "\n" +
                "fmd\n" +
                "jf\n" +
                "fj\n" +
                "\n" +
                "l\n" +
                "v\n" +
                "ntobg\n" +
                "\n" +
                "drmzvt\n" +
                "rxtsfuk\n" +
                "\n" +
                "vxdlpjkrsz\n" +
                "dgxkprvzsl\n" +
                "dsklxpvzr\n" +
                "pdvxzlrsk\n" +
                "\n" +
                "gwip\n" +
                "gakpw\n" +
                "\n" +
                "kbcadn\n" +
                "bakcd\n" +
                "\n" +
                "mhpstqcgvoalkwxinebryzujd\n" +
                "qwhirveoczyatgjdsmkpxnl\n" +
                "mejazlincwodtshxkrpgqyv\n" +
                "fsaizhnkcvwolgjpdqxtmrye\n" +
                "\n" +
                "rxubznovy\n" +
                "yvudnrbz\n" +
                "zvunwcyrkb\n" +
                "ntzbryuav\n" +
                "ndvytuzrb\n" +
                "\n" +
                "utvklrxypgbnimsdofwa\n" +
                "fyzliqswjmtpvdka\n" +
                "\n" +
                "byctfzx\n" +
                "pxzf\n" +
                "\n" +
                "g\n" +
                "ik\n" +
                "ykei\n" +
                "\n" +
                "bcajzwogvetd\n" +
                "gedbcwtzvoaj\n" +
                "hcwogaxjbzvted\n" +
                "eoczjagtdwbv\n" +
                "atvdjbcozgew\n" +
                "\n" +
                "wsclketugyaz\n" +
                "qvfbjcxtmilgow\n" +
                "\n" +
                "amgirw\n" +
                "yf\n" +
                "\n" +
                "iletugq\n" +
                "hnoxbfkaspt\n" +
                "\n" +
                "qjdfcpvksmxzywahgn\n" +
                "wnzceyskgpoxdhlmravjqf\n" +
                "xjgvhcsqyfankpzmdw\n" +
                "jyncdxwsqkvphfamgz\n" +
                "dvznygwjkcmqsxahfp\n" +
                "\n" +
                "fkuwiezpljbdayhsr\n" +
                "rphwbeujdzlfiasyk\n" +
                "erdhpafkzbwjlusiy\n" +
                "jwfhkrzdeabpliusy\n" +
                "wfipeujhylazbsrkd\n" +
                "\n" +
                "fqmbwapvouelydgicj\n" +
                "uelvqwomtyfjgcpadi\n" +
                "qkpcsdeyjiwarovnglfum\n" +
                "ijvgqdauoefpcylwbm\n" +
                "ydmqpfewaovlicugj\n" +
                "\n" +
                "sgbq\n" +
                "ltqambf\n" +
                "djbuvn\n" +
                "zmtbgy\n" +
                "\n" +
                "egvifnsaztxqcrywumj\n" +
                "aqcxujnzvfwetrhgm\n" +
                "fxdmtkgawplobqjenv\n" +
                "\n" +
                "bxuwpnl\n" +
                "ztdkau\n" +
                "\n" +
                "ecylsbdv\n" +
                "cvzlsbeyd\n" +
                "yqcveblsd\n" +
                "beyvlqcsd\n" +
                "ebsvdycl\n" +
                "\n" +
                "eb\n" +
                "xpnyter\n" +
                "\n" +
                "cbhqyzresnpxfwm\n" +
                "cwksfvhxqperbimz\n" +
                "whqzpbcsjxafre\n" +
                "\n" +
                "beodiasvj\n" +
                "jbisdoave\n" +
                "iedaovbsj\n" +
                "jxovacsiebd\n" +
                "\n" +
                "prxsnyehgwifbzo\n" +
                "ozpbsxynfiwrge\n" +
                "ribozypewsxngf\n" +
                "nyoxspzbfihgewr\n" +
                "rxzewpbnimfoysg\n" +
                "\n" +
                "shviadjcue\n" +
                "weduziolmcbngp\n" +
                "vqdieycu\n" +
                "cudeif\n" +
                "dicyuqke\n" +
                "\n" +
                "nvcwhuo\n" +
                "sltchuwnq\n" +
                "unwhci\n" +
                "\n" +
                "ekrisbvx\n" +
                "rsxiev\n" +
                "exnrvsi\n" +
                "srxevi\n" +
                "xhsvnrei\n" +
                "\n" +
                "rs\n" +
                "rs\n" +
                "sr\n" +
                "\n" +
                "fuzjmek\n" +
                "tihf\n" +
                "\n" +
                "ptlzxreqfdchibogvysmku\n" +
                "pceyizvdkqxbhrtulsfmog\n" +
                "gvkrxfsbipqedlyzomhtncu\n" +
                "suyzgrobilxhmcfdtvkeqp\n" +
                "\n" +
                "okfvjneqyicuthwsmpxl\n" +
                "wdojlsqknyhmptvicfe\n" +
                "nyfjthmpivqgsulwkboec\n" +
                "\n" +
                "ufrpkliqjgwxeybmcztasovh\n" +
                "qvkpyghxblewsaitrmzuonjc\n" +
                "giptzywrejquxkoavslcmhb\n" +
                "peaywubjozmcgrihlqsvxktf\n" +
                "lehjpzguiksacobxywtmvrq\n" +
                "\n" +
                "egryz\n" +
                "ergyz\n" +
                "yzegr\n" +
                "yfcgzre\n" +
                "\n" +
                "j\n" +
                "j\n" +
                "j\n" +
                "p\n" +
                "j\n" +
                "\n" +
                "bjt\n" +
                "tbj\n" +
                "tjb\n" +
                "tbj\n" +
                "jbt\n" +
                "\n" +
                "cklp\n" +
                "lpck\n" +
                "lckp\n" +
                "\n" +
                "fea\n" +
                "eaf\n" +
                "\n" +
                "qgm\n" +
                "dz\n" +
                "\n" +
                "yri\n" +
                "yi\n" +
                "zypdi\n" +
                "\n" +
                "ekwjxhtmgiudpz\n" +
                "xepuhgwjizkdrmt\n" +
                "ezghmliwtxujdpk\n" +
                "wdhxpjizugkemtl\n" +
                "\n" +
                "gyokbspj\n" +
                "kbgsopyj\n" +
                "pykhdsjbgio\n" +
                "opjykusbg\n" +
                "jygbsopakc\n" +
                "\n" +
                "ixorlekwgnbcjm\n" +
                "lrjkwxgie\n" +
                "wgeikxjrlh\n" +
                "rlkjxipeqgw\n" +
                "\n" +
                "ecgmdrykq\n" +
                "myrclqdgek\n" +
                "guqmzyceprkd\n" +
                "dygckwerqm\n" +
                "yrcgkiqempd\n" +
                "\n" +
                "u\n" +
                "u\n" +
                "\n" +
                "bcwnvl\n" +
                "fcvsib\n" +
                "hcnvb\n" +
                "cpgveoaby\n" +
                "ivbcn\n" +
                "\n" +
                "n\n" +
                "n\n" +
                "n\n" +
                "\n" +
                "macuqyp\n" +
                "fs\n" +
                "\n" +
                "pbout\n" +
                "suota\n" +
                "cuotm\n" +
                "atmuo\n" +
                "\n" +
                "nlravibecfj\n" +
                "eilcjafn\n" +
                "aeibjfl\n" +
                "jxfeilauo\n" +
                "jafesdnli\n" +
                "\n" +
                "xfwroij\n" +
                "fxwijor\n" +
                "irxjofw\n" +
                "rfjwboxi\n" +
                "\n" +
                "dj\n" +
                "dvj\n" +
                "dj\n" +
                "dj\n" +
                "\n" +
                "mikhxcqensrodu\n" +
                "imcvkhewgljupsxonq\n" +
                "kceuqxltinhsom\n" +
                "kzqanoemcxhius\n" +
                "vmuoxineqpzhacbks\n" +
                "\n" +
                "hklcsoaywpfrdntmu\n" +
                "xirbzckwjvpfygeno\n" +
                "\n" +
                "o\n" +
                "to\n" +
                "o\n" +
                "\n" +
                "zvirefunh\n" +
                "ezhirnvfu\n" +
                "runifzhev\n" +
                "ezivhnrfu\n" +
                "\n" +
                "zfsoducbpai\n" +
                "cupdisobazf\n" +
                "aozbsucfdiypv\n" +
                "bcfazodiups\n" +
                "\n" +
                "njfprukxamlg\n" +
                "kpfrjgynulxma\n" +
                "pijflgnuxkram\n" +
                "pkuxalrmjfgn\n" +
                "nkvrlmxustpfjga\n" +
                "\n" +
                "dszgm\n" +
                "rsmu\n" +
                "\n" +
                "iaw\n" +
                "aiw\n" +
                "wai\n" +
                "aiw\n" +
                "iwa\n" +
                "\n" +
                "s\n" +
                "s\n" +
                "s\n" +
                "sl\n" +
                "s\n" +
                "\n" +
                "eyavhnk\n" +
                "keov\n" +
                "qeiwfkcgvrpsld\n" +
                "kuvze\n" +
                "\n" +
                "a\n" +
                "mh\n" +
                "\n" +
                "ilqchdfsog\n" +
                "igscolmdzq\n" +
                "\n" +
                "fnyhxmpct\n" +
                "lchdpamfu\n" +
                "\n" +
                "vijz\n" +
                "vj\n" +
                "\n" +
                "dhpxjrmyuefclvqgni\n" +
                "uicskweohgvfryxmdq\n" +
                "tqgdifymexbwckruvh\n" +
                "\n" +
                "c\n" +
                "c\n" +
                "c\n" +
                "\n" +
                "lthidumvycszw\n" +
                "cvpqjeuhlwrfyzg\n" +
                "\n" +
                "keocuw\n" +
                "uckowe\n" +
                "oekwcu\n" +
                "cwukoe\n" +
                "\n" +
                "c\n" +
                "c\n" +
                "\n" +
                "lkxjv\n" +
                "jkvxl\n" +
                "vxklj\n" +
                "jkvxlwg\n" +
                "zkxvjly\n" +
                "\n" +
                "sqlamxeuhpgwjbdcioy\n" +
                "bumyjxsiqweholpgcda\n" +
                "gecswjlqhadiuboxmpy\n" +
                "syahibgopexwlucdqjm\n" +
                "\n" +
                "igebmv\n" +
                "tawqvezdsmpunk\n" +
                "rimocvgje\n" +
                "evmbhc\n" +
                "\n" +
                "ykjisvfatux\n" +
                "jfaisyvktux\n" +
                "itksajfxuvy\n" +
                "\n" +
                "fclkush\n" +
                "slcykdbgu\n" +
                "fskuchl\n" +
                "\n" +
                "xjhulywagzeioq\n" +
                "oejlfsquhbriayxwg\n" +
                "jiexgylwzhuqao\n" +
                "wyxhqljagieou\n" +
                "hwladixguqejyo\n" +
                "\n" +
                "sofcbhuwyqtid\n" +
                "icofdwsb\n" +
                "dfwovimbcs\n" +
                "cwibodnsxf\n" +
                "\n" +
                "jqnestpyaczfmxhwrbuvldi\n" +
                "mxanrhbfcujvyzditwlo\n" +
                "\n" +
                "ntfgivkyszmarc\n" +
                "qrajdhowuvpclbex\n" +
                "\n" +
                "kliwy\n" +
                "ukwlryi\n" +
                "ilkyw\n" +
                "\n" +
                "pmgltzsk\n" +
                "ljmipztvgow\n" +
                "zltmgup\n" +
                "umztglp\n" +
                "ftzmlpgk\n" +
                "\n" +
                "twepi\n" +
                "teq\n" +
                "\n" +
                "ohyd\n" +
                "mytjrwk\n" +
                "hfy\n" +
                "exyh\n" +
                "ye\n" +
                "\n" +
                "rzsqhtlowavy\n" +
                "twvhzyrjsqaol\n" +
                "\n" +
                "yzagcqrjeimwxokh\n" +
                "fmxtiagboleqcwdrhzk\n" +
                "opvemhasrguxkcqzwi\n" +
                "\n" +
                "atcpeyosnrjbg\n" +
                "kcesobgua\n" +
                "fagsev\n" +
                "\n" +
                "ca\n" +
                "ac\n" +
                "\n" +
                "xahmtil\n" +
                "hximtla\n" +
                "\n" +
                "hyutnjdrbsmofl\n" +
                "dswjfyothmblrnq\n" +
                "\n" +
                "et\n" +
                "te\n" +
                "eqt\n" +
                "tuje\n" +
                "\n" +
                "nbhpwzgtrcx\n" +
                "gqcxobhriznw\n" +
                "hwnbugrejxtczs\n" +
                "cujrbxfhnwzg\n" +
                "gcwzhrxndjb\n" +
                "\n" +
                "qwrfxhlyzcptvmkdeauigob\n" +
                "zbchavlkmryxiptegwfouqd\n" +
                "cfhuiptgqkoalrewzmvbyxds\n" +
                "hudmwcgbfepyitovkaqzxrl\n" +
                "\n" +
                "eysuozkm\n" +
                "ndgloqyv\n" +
                "ignhwrovy\n" +
                "\n" +
                "iqufgnvxspdcjtylkbrozh\n" +
                "inuzqktrvcxyhbgfosljdp\n" +
                "\n" +
                "qhfknsyeuirzagvcwd\n" +
                "yfcgqnxewlkrsuazhi\n" +
                "\n" +
                "lj\n" +
                "jl\n" +
                "lj\n" +
                "lyj\n" +
                "jl\n" +
                "\n" +
                "kpholfxewrdt\n" +
                "opdfhtlmkwex\n" +
                "hpwftoxderlk\n" +
                "ylxhwdofnztkpe\n" +
                "rwfpxlhtdkoe\n" +
                "\n" +
                "ubml\n" +
                "yvohg\n" +
                "zeasf\n" +
                "plum\n" +
                "qhnjxg\n" +
                "\n" +
                "cjgzwmdyuakvixlprhfe\n" +
                "kmplfuxywergchzjvani\n" +
                "xcvlzmewyujgirhpfka\n" +
                "fwhgrxkjcvpeuilzyam\n" +
                "\n" +
                "eclsiqp\n" +
                "ivgspoe\n" +
                "scepi\n" +
                "pmiadtskyze\n" +
                "\n" +
                "akmdfivwgct\n" +
                "yvgcwakhdimts\n" +
                "lcvgirakwudtp\n" +
                "aftnckwmidgv\n" +
                "\n" +
                "zuqblv\n" +
                "blvzqu\n" +
                "uvbqlz\n" +
                "qbuzvl\n" +
                "bzqxvlmu\n" +
                "\n" +
                "by\n" +
                "betlcdvry\n" +
                "yb\n" +
                "bxy\n" +
                "gybjx\n" +
                "\n" +
                "waoqdxpkmfnyrhjebcuvzs\n" +
                "qprvfczedowxknhausmyjb\n" +
                "cufdqvknwrajzybospmxeh\n" +
                "qkjzybeadvncwhxumpfsro\n" +
                "nwfkjxumpabzodvqychsre\n" +
                "\n" +
                "shdfctjrkwbvemoxluyzipnqag\n" +
                "sgbwpeuqcilxojfynmrdhvktaz\n" +
                "lhgkxfwuzbevojmrpnqydsacti\n" +
                "gflnzjasbuyimxqcvwrdpohetk\n" +
                "ynwedhbskjtvoucgapiqlzfxrm\n" +
                "\n" +
                "wlmjxp\n" +
                "ylnxoajk\n" +
                "luxjidte\n" +
                "xjrvlcdeu\n" +
                "\n" +
                "pv\n" +
                "vbpw\n" +
                "wvuap\n" +
                "kceavp\n" +
                "rdphvoitqf\n" +
                "\n" +
                "dlxzwkhtmc\n" +
                "twzhlmkdc\n" +
                "tcylhkdwzm\n" +
                "zwmlkdcth\n" +
                "gdhikmctlwsz\n" +
                "\n" +
                "hpekwtlufyragqvb\n" +
                "kbrwatlupqyfvh\n" +
                "ucbvwlhfqatpkry\n" +
                "hlakvyuqrfpwbt\n" +
                "rubvwpfqlatkhy\n" +
                "\n" +
                "npxobl\n" +
                "ckuhnplvx\n" +
                "\n" +
                "edkpjycofasulrthw\n" +
                "rpuhcdyxlftosewa\n" +
                "\n" +
                "stuvhwaexykzdorbfpi\n" +
                "shjuwgpfqmtacvlbirkzd\n" +
                "\n" +
                "frph\n" +
                "wo\n" +
                "h\n" +
                "zumtyngcj\n" +
                "pfse\n" +
                "\n" +
                "zivsgurp\n" +
                "szirpvg\n" +
                "gikvsprz\n" +
                "zigpvsrk\n" +
                "nvpsgzir\n" +
                "\n" +
                "rfimu\n" +
                "hmqrlfxpbgu\n" +
                "nrmoyftu\n" +
                "nmujfr\n" +
                "rfum\n" +
                "\n" +
                "bidzwmearovjkgcl\n" +
                "ogdbirkzqmclejvaw\n" +
                "gealcqozmijkbrvdw\n" +
                "gzakwmdbejclrivo\n" +
                "eolwifvgmrbjdazkc\n" +
                "\n" +
                "iurfyqgwk\n" +
                "ymkvqfpwrig\n" +
                "aqrfywikg\n" +
                "bfdryxikgnwoq\n" +
                "cjfgkryiuwq\n" +
                "\n" +
                "jvb\n" +
                "x\n" +
                "\n" +
                "qkxnvfuopdytrzjgbm\n" +
                "bmqkuyarjgtdpfzsnox\n" +
                "obwjxyeqtingzmdrfkplu\n" +
                "gamupstryfokbzqdxnj\n" +
                "\n" +
                "ymanp\n" +
                "npfshjya\n" +
                "pundyklatc\n" +
                "ypfanh\n" +
                "\n" +
                "garp\n" +
                "grpa\n" +
                "arpg\n" +
                "argp\n" +
                "\n" +
                "inedmtpwrvub\n" +
                "vwibertnudmp\n" +
                "idurbepwtmnv\n" +
                "\n" +
                "yczoaplwmxibqgsfn\n" +
                "wbiuxyqzpncvgmsl\n" +
                "gpoltrbisqfznwxcymj\n" +
                "\n" +
                "a\n" +
                "a\n" +
                "a\n" +
                "a\n" +
                "\n" +
                "cgjviyufped\n" +
                "pcuvygzkjid\n" +
                "ptvigyjdcku\n" +
                "\n" +
                "u\n" +
                "i\n" +
                "tqa\n" +
                "j\n" +
                "ul\n" +
                "\n" +
                "zitbfuer\n" +
                "uzfithernb\n" +
                "uftbzire\n" +
                "uitefbzr\n" +
                "\n" +
                "jcwkroamnegxvqsh\n" +
                "kejhanqmvcrxwsog\n" +
                "gaqmkexjvcsnrowh\n" +
                "\n" +
                "taegslmuyqcipz\n" +
                "asytxrgdpfbcqliwz\n" +
                "tpgoschavqjlkyzi\n" +
                "\n" +
                "oc\n" +
                "oc\n" +
                "oc\n" +
                "co\n" +
                "\n" +
                "mrfvjlykquz\n" +
                "fzmvuleykqt\n" +
                "vykmzlgquf\n" +
                "kqfzuvygetml\n" +
                "\n" +
                "a\n" +
                "s\n" +
                "\n" +
                "ionve\n" +
                "eailo\n" +
                "jiomexwh\n" +
                "beziqpdco\n" +
                "ihtoe\n" +
                "\n" +
                "cfjvrqosnwyedaubmhgtlxzk\n" +
                "olxzjfwrcytkbgudasvqhnme\n" +
                "tuwfnckrzsvjgbxdmyhqlaeo\n" +
                "txnydgufbmjaqkrzlwhoevcs\n" +
                "bgakxqmfsdwyjvelntchzour\n" +
                "\n" +
                "njvkobzs\n" +
                "bsjvkwn\n" +
                "\n" +
                "qmnluxw\n" +
                "ovgtikpdbrya\n" +
                "nchfsjqez\n" +
                "\n" +
                "khtdryej\n" +
                "hdrtv\n" +
                "qnaodtm\n" +
                "\n" +
                "as\n" +
                "aus\n" +
                "\n" +
                "omjaixvgklq\n" +
                "vgkaxjihdrlq\n" +
                "ycxkzatpusiljqgv\n" +
                "\n" +
                "jtepylmrqbiwk\n" +
                "xerlpmynqtkfbjwi\n" +
                "timwpbkegljqry\n" +
                "lqijkebmgpwyrt\n" +
                "qrkljpbytemiw\n" +
                "\n" +
                "q\n" +
                "xqint\n" +
                "dkqb\n" +
                "\n" +
                "trjmdxpoeqcwf\n" +
                "tfedxqcprwom\n" +
                "kmftwxqporncde\n" +
                "\n" +
                "fpcmndhr\n" +
                "dzepjngqikcfrh\n" +
                "nhfpcrd\n" +
                "\n" +
                "c\n" +
                "c\n" +
                "c\n" +
                "y\n" +
                "c\n" +
                "\n" +
                "t\n" +
                "t\n" +
                "ti\n" +
                "\n" +
                "tgfspxdy\n" +
                "sytgpfxd\n" +
                "\n" +
                "zov\n" +
                "voz\n" +
                "ovz\n" +
                "\n" +
                "ic\n" +
                "ieuc\n" +
                "\n" +
                "vhesndkizjgwcpobulam\n" +
                "szjymxwopckfqtgdib\n" +
                "\n" +
                "jdfzgqsbrmnticl\n" +
                "fbcdgqtznmjri\n" +
                "doitrczjqfbgmn\n" +
                "otzbjfidmnrqcg\n" +
                "\n" +
                "cb\n" +
                "bc\n" +
                "cb\n" +
                "cb\n" +
                "\n" +
                "aspjvghyurx\n" +
                "vcarwsbh\n" +
                "laeshvzrb\n" +
                "hsrvia\n" +
                "\n" +
                "kpxzdhasfmltouvrc\n" +
                "duvpkascromz\n" +
                "vmcskupzorad\n" +
                "\n" +
                "pguayqbwm\n" +
                "gpyaqbwum\n" +
                "ywaqgpmbu\n" +
                "\n" +
                "ypdlnjse\n" +
                "elskbyz\n" +
                "jesylo\n" +
                "lyse\n" +
                "\n" +
                "zlokqmjiurpwgbn\n" +
                "xzvurhgmlkwqnibjpo\n" +
                "\n" +
                "wpzenbojcykqxvt\n" +
                "wnyzlbjkeoqtvcpx\n" +
                "itkjzydbpvoxcewnq\n" +
                "\n" +
                "gfuvenodsizwmh\n" +
                "hwfuvsntdg\n" +
                "\n" +
                "gkibnpalc\n" +
                "inkcgpal\n" +
                "gnpzliakfc\n" +
                "\n" +
                "ibektdpuhg\n" +
                "iwbgjke\n" +
                "iycnergfqkbo\n" +
                "egxadvlmbijk\n" +
                "\n" +
                "l\n" +
                "yjg\n" +
                "l\n" +
                "\n" +
                "ymuoc\n" +
                "oymcu\n" +
                "oymcu\n" +
                "youcm\n" +
                "ycomu\n" +
                "\n" +
                "wifoqy\n" +
                "zksfrict\n" +
                "bdpvhuilgejn\n" +
                "acoi\n" +
                "mqi\n" +
                "\n" +
                "qrcukhwvzdjilpto\n" +
                "hqrmwkupclvjtizo\n" +
                "\n" +
                "gdizlfawobuk\n" +
                "dihqfswcgukzrbla\n" +
                "gmukawbdfizlo\n" +
                "\n" +
                "zwdrpv\n" +
                "dzvpwr\n" +
                "\n" +
                "ycidkpfrqjelha\n" +
                "pjahykfecdqrli\n" +
                "kfqlajhdepyirc\n" +
                "pkhaceijlqdfry\n" +
                "\n" +
                "pwuxbqotey\n" +
                "okbphqutfx\n" +
                "xvsgodubtlpqijr\n" +
                "puoewaxtbmq\n" +
                "\n" +
                "qtbaoex\n" +
                "xpoqa\n" +
                "agiweqtop\n" +
                "nozuadmjrq\n" +
                "\n" +
                "huvqdaij\n" +
                "fkuvaijdhq\n" +
                "\n" +
                "biewrdlzc\n" +
                "rjlcikbzmdwve\n" +
                "leucwfpoizndbxr\n" +
                "\n" +
                "avgtnubqcpxrhwdoml\n" +
                "vrkqgyndcmohtupswa\n" +
                "\n" +
                "dmjqfesnxyciz\n" +
                "hfzudcjxsmno\n" +
                "mfjhrcsxznd\n" +
                "lcmbjnxzfadrs\n" +
                "\n" +
                "tvayrhpqskd\n" +
                "qrtkvhyus\n" +
                "epjsytzhvrqk\n" +
                "yzqohmvtgsrk\n" +
                "hvlysqtwirbk\n" +
                "\n" +
                "ieyd\n" +
                "aipeyg\n" +
                "\n" +
                "r\n" +
                "rg\n" +
                "rm\n" +
                "r\n" +
                "\n" +
                "qcweajhfmlgyzpv\n" +
                "ouqdxmsphkbatenr\n" +
                "\n" +
                "fba\n" +
                "kfba\n" +
                "baf\n" +
                "\n" +
                "vxpblsyjnrmkai\n" +
                "vpyhagcwqbzxmik\n" +
                "rpbytexdijnfavkom\n" +
                "\n" +
                "fpmytnk\n" +
                "cyaw\n" +
                "\n" +
                "jhyimdg\n" +
                "mhyij\n" +
                "hmvyij\n" +
                "mihezcovyj\n" +
                "yhmciej\n" +
                "\n" +
                "sqfaopkgze\n" +
                "kxsecfphozq\n" +
                "qsotezpfk\n" +
                "\n" +
                "ewcvoaurmjhq\n" +
                "cuqvjwreaohm\n" +
                "ewvjmqacuorh\n" +
                "wauhojecqmvrs\n" +
                "\n" +
                "lyieuqdjcb\n" +
                "vkpctdmywzsreubn\n" +
                "delchbujy\n" +
                "jbcyegdou\n" +
                "xduayceb\n" +
                "\n" +
                "nidxswarcqtk\n" +
                "kciqdarnbewsxt\n" +
                "acqrdkntipxlsw\n" +
                "ikpawtcdsqnrx\n" +
                "\n" +
                "gikrfhwltveap\n" +
                "yeplvatowncgxirf\n" +
                "griadtewmvblpf\n" +
                "\n" +
                "htjkmzxlvbygcwqioe\n" +
                "jzwtymxvigbheolckq\n" +
                "cxmvjyklobhtwgqzie\n" +
                "teczbxvlmgojqiwkyh\n" +
                "oxvejlbtiqywhzgmkc\n" +
                "\n" +
                "jkfapozdwcie\n" +
                "bmushwjgltrn\n" +
                "\n" +
                "rpnbxkoij\n" +
                "exjdri\n" +
                "uirjegxsa\n" +
                "\n" +
                "zawoncbymgsrhv\n" +
                "dvctxgeusr\n" +
                "cvizgyhlmrwsfp\n" +
                "\n" +
                "shnyujedctwfq\n" +
                "yscahxndftreq\n" +
                "\n" +
                "xrnysi\n" +
                "itcluvmd\n" +
                "niqwozjber\n" +
                "\n" +
                "gjobshlayxvctnfq\n" +
                "ljcxaonvbstqfgyh\n" +
                "ybhxgntqcsvfaojl\n" +
                "rjoxblqavncusgheytf\n" +
                "sncqlvybxfjtghao\n" +
                "\n" +
                "uozb\n" +
                "ldewrck\n" +
                "xbg\n" +
                "xhg\n" +
                "z\n" +
                "\n" +
                "yubqaznf\n" +
                "imwhrgnkjls\n" +
                "\n" +
                "msvgjrnkcloaup\n" +
                "csxjnkgrpiuoveamy\n" +
                "pknvrajmcudswgzo\n" +
                "tnupacsxrgkvmoji\n" +
                "bpnkfarqumsvhcojg\n" +
                "\n" +
                "bzvyuenaihfdcgwk\n" +
                "puchyenmzgksrijoa\n" +
                "ugebciktnlzhay\n" +
                "\n" +
                "cedfutpnsivjlobrkaxy\n" +
                "denscvpbmlkxaojrfh\n" +
                "\n" +
                "vugjrq\n" +
                "jqgtuwcnrv\n" +
                "grvkuqj\n" +
                "gbmvqsyxjueplzirhf\n" +
                "avudnjqgr\n" +
                "\n" +
                "vpidajtmgozxwuksh\n" +
                "ughiwmakpjszdtvox\n" +
                "wugipxzdvastkhmj\n" +
                "sxughjakmnwfpdivzt\n" +
                "wimvaupjhgxstkzd\n" +
                "\n" +
                "mqsuwhdxpcozfr\n" +
                "rsdwhfpakzxjmo\n" +
                "eysprldfqzowmhx\n" +
                "fodhrtmswxyzp\n" +
                "\n" +
                "vsmzfbjhwqxiugtlc\n" +
                "gcqdsfmpletnhbxr\n" +
                "\n" +
                "uxbgkfjwesmlchr\n" +
                "feakldxqnpwcjgvrzbhs\n" +
                "hjosrixfmlcgbkew\n" +
                "\n" +
                "dszv\n" +
                "zsvd\n" +
                "vsdz\n" +
                "zvds\n" +
                "sdzv\n" +
                "\n" +
                "pdw\n" +
                "lxudjpiwz\n" +
                "advnkpqw\n" +
                "hswpdog\n" +
                "\n" +
                "gslpira\n" +
                "neuzf\n" +
                "\n" +
                "ifjt\n" +
                "tjif\n" +
                "jfit\n" +
                "jitf\n" +
                "ifktj\n" +
                "\n" +
                "jrnzb\n" +
                "unkjshpe\n" +
                "njza\n" +
                "\n" +
                "ydigxaqm\n" +
                "iaeokqgmyhr\n" +
                "\n" +
                "bkxmngtdlyev\n" +
                "nmbuzoveixlprkys\n" +
                "\n" +
                "zjloghmtu\n" +
                "ermvzn\n" +
                "qzdncfm\n" +
                "afczxmp\n" +
                "\n" +
                "aptscynieqmfgjhbr\n" +
                "bmsirnafyepthgcqj\n" +
                "\n" +
                "q\n" +
                "qlr\n" +
                "fq\n" +
                "qk\n" +
                "\n" +
                "v\n" +
                "v\n" +
                "\n" +
                "ucrmbsozjkfy\n" +
                "buscrmofkzy\n" +
                "uosmfkryzbc\n" +
                "sqirbfzmocuynk\n" +
                "mbucykofrzs\n" +
                "\n" +
                "lrp\n" +
                "plz\n" +
                "lrp\n" +
                "lp\n" +
                "lp\n" +
                "\n" +
                "yfzmpgcsw\n" +
                "prycgfm\n" +
                "rfcmgpy\n" +
                "scgmyqpf\n" +
                "flcyvpohmgu\n" +
                "\n" +
                "g\n" +
                "g\n" +
                "g\n" +
                "e\n" +
                "\n" +
                "lxoaibjch\n" +
                "wudyrfvkzn\n" +
                "gtpmkeyqd\n" +
                "\n" +
                "zjhlwbtfuvick\n" +
                "wujtvblzchkif\n" +
                "\n" +
                "ksdfpvqbtxaluneo\n" +
                "dqofprhnxamskujeb\n" +
                "\n" +
                "hacwigyftqblx\n" +
                "xwlqahitbgcyf\n" +
                "ahyxlwgtqifbc\n" +
                "\n" +
                "mb\n" +
                "m\n" +
                "mg\n" +
                "m\n" +
                "\n" +
                "ecrasdtyljuqimhnwfb\n" +
                "qleiaydjcugrwn\n" +
                "jdyewaqnrcliu\n" +
                "\n" +
                "g\n" +
                "lqfio\n" +
                "adhstybz\n" +
                "\n" +
                "gryzuxenhlvopbtmfwqcas\n" +
                "yeqzalmogbncxpsfujwh\n" +
                "mflqzhoaupcseygnbwx\n" +
                "myswzuonfqlaxecbhpgj\n" +
                "\n" +
                "uwvzati\n" +
                "uzcjvtai\n" +
                "savuizt\n" +
                "atiuzv\n" +
                "\n" +
                "cozuin\n" +
                "abuizo\n" +
                "tiozua\n" +
                "wilfzeoqu\n" +
                "roictxuz\n" +
                "\n" +
                "gndpkojqu\n" +
                "gunkpsjoa\n" +
                "rtmzjpgkovwxlnuc\n" +
                "\n" +
                "lrj\n" +
                "rjl\n" +
                "mrjl\n" +
                "\n" +
                "udlpevjgzrfawitqs\n" +
                "qgrtiujslfeovza\n" +
                "surivgtfqjleaz\n" +
                "ezavgjtlfrusiq\n" +
                "\n" +
                "g\n" +
                "fx\n" +
                "mf\n" +
                "tx\n" +
                "iyqd\n" +
                "\n" +
                "sljgmdztynvrqexhwfi\n" +
                "gvwdyerlqnxthmjifsz\n" +
                "qgmjlfwrxztynivdhse\n" +
                "\n" +
                "zkvuir\n" +
                "kvruiz\n" +
                "vriukz\n" +
                "kriumzv\n" +
                "zruikv\n" +
                "\n" +
                "zyqgnvda\n" +
                "kdygvqanz\n" +
                "zyagvqdnu\n" +
                "qnwdmlaxgzyfvo\n" +
                "dnzgyavq\n" +
                "\n" +
                "o\n" +
                "s\n" +
                "q\n" +
                "\n" +
                "cbroy\n" +
                "qiyocmjdt\n" +
                "uyoc\n" +
                "\n" +
                "lkqj\n" +
                "kjql\n" +
                "jqlk\n" +
                "ljqk";
        return values.split("\n\n");
    }

}
